apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: va7cuuh6p-go 
  janus-idp.io/tekton: va7cuuh6p-go
  backstage.io/kubernetes-id: va7cuuh6p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: va7cuuh6p-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml